# Generated by Django 4.2.1 on 2023-08-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
